- extmod/modtrezormsg/modtrezormsg.c
It is useful for me (in the extension) to recognize if the emulator is turned on or off, so I can handle all the states gracefully.
So I added a hack - on a special "ping" message - 64 * 255 - I send back the same thing. It's purposefully away from the micropython code.
> Adding UDP ping

- docs/README.md
- docs/hardware.md
This is a rough draft (not ready to be merged) to get the discussion going.
I'm trying to piece together what is needed from the code, and searching Google.
For example, there are some TODOs with questions.
Referencing https://github.com/trezor/trezor-core/issues/8
> docs: add reference hardware and dev kit info

- embed/trezorhal/stm32_it.c
I noticed this while working on the startup code. To me, it seems unsafe to print memory to the display when that could potentially include sensitive things. What do you think?
> hardfault handler update

- embed/bootloader/startup.s
- embed/firmware/startup.s
- embed/trezorhal/util.s
these should close out https://github.com/trezor/trezor-core/issues/12
> boardloader, bootloader, firmware stage switching updates for issue #12

- README.md
- docs/bootloader.md
STLINK_VER related documentation update and some notes about the boardloader
> doc: STLINK_VER and boardloader description

- docs/hardware.md
Mainly updating the dev kit info to use USB HS. Some other minor updates too.
> docs: dev kit hardware updates mainly usb

- docs/memory.md
- embed/boardloader/memory.ld
- embed/bootloader/memory.ld
- embed/firmware/memory.ld
just reviewing today's changes and saw this could be updated
> stm32f427 sram bigger

- embed/trezorhal/stm32.c
just being a little more conservative. i put this on the scope and it works fine. the prior version works too on the f427, just this seems slightly safer.
> SystemInit: add more waiting just to be sure

- embed/boardloader/main.c
- embed/boardloader/startup.s
- embed/bootloader/main.c
- embed/bootloader/startup.s
- embed/firmware/main.c
- embed/firmware/startup.s
setup the stack protector for the stage before main function
> startup: setup the stack protector for the stage before main function

- SConscript.boardloader
- SConscript.bootloader
- SConscript.firmware
> SConscript: trivial string concat cleanup

- README.md
- docs/hardware.md
follows-up to the python3 updates.
other trivial doc updates too.
> docs: pip to pip3 no cache, add some hardware details

- embed/trezorhal/common.c
- embed/trezorhal/util.s
linking in discussion https://github.com/trezor/trezor-core/commit/6738796d8b0c5eb73a3467e66483b31d4c0b4231
> clear_otg_hs_memory: remove unpredictable write

- embed/trezorhal/secbool.h
trivial addition of the unsigned suffix to the literals
> secbool: trivial addition of the unsigned suffix to the literals

- src/apps/common/request_passphrase.py
- src/apps/common/request_pin.py
- src/apps/common/seed.py
- src/apps/common/storage.py
- src/apps/homescreen/__init__.py
- src/apps/management/apply_settings.py
- src/apps/management/load_device.py
- src/boot.py
- src/main.py
- src/trezor/loop.py
Builds on top of #56, mostly Python changes.
> Unlock storage after boot

- Makefile
- embed/bootloader/main.c
- embed/extmod/modtrezorui/display-stm32.h
- embed/extmod/modtrezorui/display-unix.h
- embed/extmod/modtrezorui/display.c
- embed/firmware/main.c
- embed/trezorhal/touch.c
- embed/trezorhal/touch.h
I'd like for someone to try this with ST7789V and let me know if it fails.
I don't think it'll be too far off since it works great for ILI9341.
> display: driver cleanup

- docs/memory.md
- embed/boardloader/main.c
- embed/bootloader/messages.c
- embed/extmod/modtrezorconfig/modtrezorconfig.c
- embed/extmod/modtrezorconfig/norcow.c
- embed/extmod/modtrezorconfig/norcow.h
- embed/extmod/modtrezorconfig/storage.c
- embed/extmod/modtrezorconfig/storage.h
- embed/trezorhal/flash.h
- src/apps/management/change_pin.py
- src/boot.py
Instead put a small area into the norcow sector.
> Remove PIN failure area

- src/apps/management/backup_device.py
Fixes https://github.com/trezor/trezor-core/issues/137
> src/apps/management: delay flag setting by one step in backup

- src/apps/wallet/sign_tx/signing.py
This commit only rearranges the `if` main branch, so the segwit branch
has priority over bip143. Since Bitcoin Gold is allowing both segwit and
forcing bip143, the bitcoin gold segwit transactions were failing.
updates #147
> wallet/signing: segwit has priority over force_bip143

- docs/build.md
Following cf9c97288eff9464bd8cf264f8e1ba4776ad1ab9.
> docs: fix 'vendorheader' to 'vendor' at build.md

- src/apps/wallet/__init__.py
- src/apps/wallet/ecdh.py
- src/apps/wallet/sign_identity.py
- src/trezor/utils.py
Tested both with NIST256 and Curve25519 GnuPG keys:
(similar to https://github.com/trezor/trezor-mcu/commit/c86086e2b90e0a2e547d661766e05585d2cf54f5)
> apps/wallet/ecdh: support decryption (for GnuPG)

- src/apps/wallet/ecdh.py
- src/apps/wallet/sign_identity.py
This PR should make signature/decryption dialogs a bit nicer (compared to https://github.com/trezor/trezor-core/pull/158):
What do you think?
> apps/wallet/{sign_identity, ecdh}: show protocol as part of the header

- embed/extmod/modtrezorui/display.c
Note that qrenc submodule should also be updated.
> display: show qr-code correctly (was mirrored)

- src/apps/common/confirm.py
- src/apps/common/request_passphrase.py
- src/apps/common/seed.py
- src/apps/ethereum/sign_tx.py
- src/apps/management/apply_settings.py
- src/apps/management/backup_device.py
- src/apps/management/change_pin.py
- src/apps/management/load_device.py
- src/apps/management/recovery_device.py
- src/apps/management/reset_device.py
- src/apps/management/set_u2f_counter.py
- src/apps/wallet/cipher_key_value.py
- src/apps/wallet/sign_message.py
- src/apps/wallet/sign_tx/__init__.py
- src/apps/wallet/verify_message.py
- src/trezor/wire/__init__.py
- src/trezor/wire/errors.py
Makes the error API much more ergonomic.
> src/trezor/wire: add exceptions for all defined FailureTypes

- docs/testing.md
- pytest.ini
- tests/run_tests_device_emu.sh
as per https://github.com/trezor/python-trezor/pull/263
> custom runxfail for better testing of new feature PRs

- src/apps/homescreen/__init__.py
- src/apps/wallet/sign_tx/__init__.py
This is just a tiny refactoring of the init function in the wallet, `isinstance` is now used. Tests are passing, so good to merge?
> wallet: isinstance in __init__

- embed/extmod/modtrezorui/display.h
- embed/extmod/modtrezorui/modtrezorui-display.h
- src/trezor/ui/text.py
> Efficient text layout

- embed/bootloader/messages.c
- embed/bootloader/messages.h
> bootloader: ask again for block if invalid

- src/apps/ethereum/layout.py
Change was not included in last PR.
> Apply RSKIP-60 in require_confirm_tx

- build-docker.sh
Similar to recent trezor-mcu changes
> Docker: support local build and build from other gh repos

- setup.cfg
- src/apps/ripple/README.md
- src/apps/ripple/__init__.py
- src/apps/ripple/base58_ripple.py
- src/apps/ripple/get_address.py
- src/apps/ripple/helpers.py
- src/apps/ripple/layout.py
- src/apps/ripple/serialize.py
- src/apps/ripple/sign_tx.py
- src/main.py
- src/trezor/crypto/base58.py
- tests/test_apps.ripple.pubkey_to_address.py
- tests/test_apps.ripple.serializer.py
This introduces a support for Ripple. Only simple payments are supported. The only thing missing is a README, which I'll add soon.
> Ripple support

- embed/extmod/modtrezorui/display-stm32.h
I found another ID register in the datasheet for the ILI9341. 0xD3 is not mentioned in the ST7789V datasheet. That is why I only read the register if we don't already have a positive identification from the 0x04 register.
tested on prototype board + st7789v and with dev kit + ili9341.
> display_identify: improve identification of ILI9341

- src/apps/cardano/get_public_key.py
- src/apps/common/display_address.py
- src/apps/common/show.py
- src/apps/ethereum/get_address.py
- src/apps/ethereum/verify_message.py
- src/apps/lisk/get_address.py
- src/apps/lisk/get_public_key.py
- src/apps/lisk/layout.py
- src/apps/nem/get_address.py
- src/apps/ripple/get_address.py
- src/apps/ripple/layout.py
- src/apps/stellar/get_address.py
- src/apps/stellar/get_public_key.py
- src/apps/wallet/get_address.py
- src/apps/wallet/get_public_key.py
- src/apps/wallet/verify_message.py
> GetPublicKey consolidation

- src/apps/common/signverify.py
- src/apps/ethereum/sign_message.py
- src/apps/ethereum/verify_message.py
- src/apps/lisk/sign_message.py
- src/apps/nem/layout.py
- src/apps/nem/mosaic/layout.py
- src/apps/nem/transfer/layout.py
- src/apps/wallet/sign_message.py
- src/apps/wallet/verify_message.py
- src/trezor/ui/text.py
- src/trezor/utils.py
`split_words` and the `Text` component implement the same layout algorithm.
Fixes #330
> Remove split_words

- src/apps/fido_u2f/__init__.py
- src/boot.py
- src/trezor/loop.py
- src/trezor/messages/__init__.py
If the exceptions are not handled as part of the program logic at least log them. Now you can find out when you run out of memory etc.
> firmware: log exceptions in debug mode (no silent unhandled exceptions)

- embed/trezorhal/touch_t.h
Because CTPM dislikes being polled when no touches are seen, keeps resetting, and maybe freezes once in a while. This is very likely a fix for #334.
Before, we would simply read the touch registers on every loop. Now we first check whether the interrupt line is down, which indicates that the CTPM has data to tell us.
Tracking the `touching` flag is necessary, as sometimes we don't poll frequently enough to catch the TOUCH_END event before interrupt line goes up again.
The `last_packet` handling miiight not be necessary - AFAICT, the CTPM has some sort of buffer and always returns TOUCH_START at first and TOUCH_END at last. Still, better safe than sorry.
---
I'm still testing whether #334 is actually fixed with this. But this patch is likely correct in any case.
> embed/trezorhal: only poll CTPM when touch is detected

- embed/extmod/modtrezorui/display-unix.h
- src/trezor/ui/__init__.py
- src/trezor/ui/button.py
- src/trezor/ui/confirm.py
- src/trezor/ui/pin.py
- src/trezor/ui/text.py
> Reduce flickering, fix MacOS Mojave issues

- src/apps/ethereum/verify_message.py
Ethereum's verify_function takes an actual address as an argument not a
derivation path. So any path validation does not make any sense.
Also, if the verify_recover function raises an exception, it gets
propogated as a DataError (additional fix for #422).
> eth/verify: path is not validated; improve invalid signature handling

- docs/CONTRIBUTING.md
A CONTRIBUTING file with a link to our wiki.
> docs: contributing file

- src/apps/fido_u2f/knownapps.py
E.g. see https://twitter.com/bitwarden.
> u2f: capitalize Bitwarden

- src/trezor/ui/num_pad.py
To easily enter numbers from an arbitrary range. I've decided to go with the design where as much buttons are present as possible, because then 32 (the max number of shares in SLIP-39) fits in three pages.
For a perfect UI maybe a back button should be present when you click some + button? So you can go back
> NumPad to enter a number from arbitrary range easily

- docs/CONTRIBUTING.md
I guess this is how you check if your contributors really read the guidelines. I'm proud that I passed the test.
> docs: Use proper make targets for code style

- src/trezor/ui/num_pad.py
- src/trezor/ui/style.py
Adds back button to return to previous screen and improves style.
> ui: add back button to NumPad

- tests/run_tests.sh
* show the number of passed and failed tests
* allow the user to stop running tests via CTRL+C
* colorize the output
> Update run_tests.sh: show totals, allow interrupts, add colors

- src/apps/wallet/sign_tx/__init__.py
- src/apps/wallet/sign_tx/helpers.py
- src/apps/wallet/sign_tx/layout.py
- src/apps/wallet/sign_tx/signing.py
- tests/test_apps.wallet.segwit.signtx.native_p2wpkh_grs.py
- tests/test_apps.wallet.segwit.signtx.p2wpkh_in_p2sh_grs.py
Dates need work on embed platforms. All tests pass.
> #506 display custom locktime

- src/apps/webauthn/__init__.py
> u2f: pad last packet with zeros

- .gitignore
- tests/run_tests_device_emu_monero.sh
Testing with the official Monero binary client and trezor tests.
> tests: monero binary test added

- tests/run_tests_device_emu_monero.sh
After @MrMebelMan feedback I've added some quotes to make script more safe. @tsusanka sry for additional pr.
> tests: minor monero script test fix, quotes
