Makefile.firmware
Makefile.loader
micropython/bootloader/main.c
micropython/firmware/header.S
micropython/firmware/main.c
micropython/firmware/memory.ld
micropython/firmware/version.h
micropython/loader/header.S
micropython/loader/main.c
micropython/loader/memory.ld
micropython/loader/version.h
micropython/trezorhal/common.h

Put the 512 byte loader and firmware header into the image.
Fix the addresses of the vector table.

Put loader/firmware header into image

---

README.md
docs/hardware.md
embed/extmod/modtrezorui/display-stm32.h

the compile time bug only occurs when compiling with DISPLAY_ILI9341V for that type of display.
the rest of the changes are comment adds and documentation updates.

fix minor compile time bug and update docs

---

Makefile
SConscript.boardloader
SConscript.bootloader
SConscript.firmware
embed/extmod/modtrezorui/display-stm32.h
embed/extmod/modtrezorui/display.h
embed/trezorhal/common.c

My current test display is ILI9341 and doesn't have the tearing effect line connected.
The build changes scratch that itch while defaulting to what you had already.
Example usage:
`make build_boardloader TEARING_EFFECT=1 DISPLAY_ILI9341V=1`
I removed the red flash on fatal error to avoid possibly triggering epileptic seizures for people.
Code review question:
Does the ST7789V really use RGB while the ILI9341V uses BGR? I tested with the ILI9341 and BGR works for it. I don't have my ST7789V display yet.

better support ILI9341 testing, make tearing effect synch optional, minor fixes

---

Makefile
README.md

openocd is solid and this removes dependency on another tool, st-flash.
Tested:
```
make openocd STLINKv21=1
make flash STLINKv21=1
make flash_erase STLINKv21=1
make flash_boardloader STLINKv21=1
make flash_bootloader STLINKv21=1
make flash_firmware STLINKv21=1
make combine flash_combine STLINKv21=1
```

transition to openocd from st-flash

---

docs/hardware.md

The most important change here is syncing up the LCD_PWM PB13 to PA7 change.
Also added some more specifics.
By the way, what does SBU stand for? embed/trezorhal/sbu.h

docs: hardware updates

---

embed/boardloader/main.c
embed/bootloader/main.c
embed/extmod/modtrezorui/display-stm32.h
embed/extmod/modtrezorui/display-unix.h
embed/extmod/modtrezorui/display.c
embed/extmod/modtrezorui/display.h
embed/extmod/modtrezorui/modtrezorui-display.h
embed/firmware/main.c

1) Smoothed out the display (re)initializing and clearing to reduce flashing during startup and clear the whole display for 240x320 displays.
Also, removing the `display_init` from the python binding fixes some sporadic artifacts on the trezor.io/start message (the initial screen after the 1 second green SL logo).
With these changes, there is only one white flash at the very beginning, before the display is initialized. That may be solvable by hardware design on the backight pin (just a guess, I did not try this).
Tested with:
```
make build_boardloader DISPLAY_VSYNC=0 DISPLAY_ILI9341V=1
make build_bootloader DISPLAY_VSYNC=0 DISPLAY_ILI9341V=1
make vendorheader
make build_firmware DISPLAY_VSYNC=0 DISPLAY_ILI9341V=1
```
2) Some function brace cleanup while I was touching the files.

display related updates, flashing++

---

Makefile

I find these helpful.
I was thinking about leaving the original `gdb` rule alone, in-case you like how it works for firmware debugging (or making `gdb_firmware` the new `gdb`).
I tend to prefer the automatic `monitor reset halt` and lack of confirmation prompts as well as separate targets for different symbols.

Makefile GDB updates

---

embed/trezorhal/flash.c

I was compiling a test with `CCFLAGS='-Og '` instead of `CCFLAGS='-Os '` and came across this:
```
embed/trezorhal/flash.c: In function 'flash_otp_write':
embed/trezorhal/flash.c:123:12: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]
return ret;
```

flash_otp_write: uninitialized variable

---

embed/boardloader/startup.s
embed/bootloader/startup.S
embed/firmware/main.c
embed/firmware/startup.S
embed/trezorhal/common.c
embed/trezorhal/stm32_system.c

It seemed awkward/unclean to me that the clock configs were forgotten and reconfigured by each stage (the `SystemInit` + `periph_init` combo).
My preference is to setup the clock tree early in the boardloader and then be able to bring peripherals online that depend on the clock settings, like the TRNG, as needed.
For example, I'd like to have the HSE+PLL+CSS and TRNG setup before wiping memory so that it could be wiped with unpredictable data (a follow-up to this PR).
These changes configure the PLLM  to 4 instead of 8 to adhere to the RM0090, section 7.3.2, recommendation that: "The software has to set these bits correctly to ensure that the VCO input frequency ranges from 1 to 2 MHz. It is recommended to select a frequency of 2 MHz to limit PLL jitter."
Some unnecessary stuff, like …

clock related updates

---

embed/boardloader/main.c
embed/extmod/modtrezorui/display-stm32.h

Minor updates for your last commit 6693d61aa072d831d77ffad02a66892873ab1220
1) turn on back light to see `copy_sdcard` output
2) use `display_backlight` instead of `display_set_backlight` to also set `DISPLAY_BACKLIGHT` in embed/extmod/modtrezorui/display.c
I like that you turn the back light off earlier now. Good idea. At one point, I was thinking of only using the display in the boardloader for the SD card update messages. But, then I decided to leave the display init in the normal boot flow so that the display memory got cleared.

display: minor backlight handling

---

embed/boardloader/memory.ld

More prep work that makes the bootloader and firmware portion of #12 much easier.
I have the bootloader and firmware updates too. I'll push them up later, after more testing.
1) The changes like this: `KEEP(*(.text))` to `*(.text*)`
These changes fully embrace the link time garbage colector and remove the reliance on details of orphan section processing.
The script is much more intuitive now. I'm glad that I got past the mental block that made me want to use the `KEEP`s.
2) Sets the FLASH memory region to 32K to act as a build time assertion on the code size
3) Other trivial general cleanup/simplifying changes

boardloader: simplify linker script

---

embed/trezorhal/util.s

we zero out memory, might as well get the registers too. the motivation behind this was that i wanted to make sure that the rng data used for memory clearing was not leaked to a later stage.

jump_to: reset registers to zero

---

embed/boardloader/main.c
embed/trezorhal/common.c
embed/trezorhal/common.h

I looked into the peripherals mentioned in https://github.com/trezor/trezor-core/issues/34. Only the USB OTG HS seemed interesting as far as harboring data.
I found that I needed to enable the clock to the peripheral in order to read and write the data, but that was it. I didn't have to set it up more. So, clock it, write the local memory, and unclock it.
I don't think that leaves any unintended side-effects. It doesn't appear to as far as I tested.
Here's a good test:
1. in gdb, find nothing with: `find 0x40060000,0x4007ffff,"arise! chikun arise!"`
1. `./trezorctl ping "arise! chikun arise!"`
1. in gdb, find a bunch of references with the same find command from step 1
1. Reset the device and step through and pay attention to when the data becomes visible and when it goes away. You'll …

boardloader: issue #34

---

Makefile

This saves me time and makes sure that I am working with fresh versions of the files. Not doing both has bitten me a couple of times.
Without the recursive, you don't get all the submodules. Without force, you can have stale versions of the files.
This shows what additional modules the recursive part picks up:
```
> git submodule update --init
Submodule 'vendor/micropython' (https://github.com/trezor/micropython.git) registered for path 'vendor/micropython'
Submodule 'vendor/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'vendor/nanopb'
Submodule 'vendor/norcow' (https://github.com/trezor/norcow.git) registered for path 'vendor/norcow'
Submodule 'vendor/trezor-common' (https://github.com/trezor/trezor-common.git) registered for path 'vendor/trezor-common'
Submodule …
```

Makefile: vendor target add --recursive and --force

---

embed/trezorhal/vectortable.s

First, I changed some zero definitions to `architecture_reserved_handler` which just winds up setting the `default_handler` for those entries. This is just a little cleaner to me. Technically, the zero definitions are invalid entries that would cause a UsageFault and wind up at the `default_handler` anyways because according to the ARMv7-M manual section B1.5.3, "entries
must have bit[0] set to 1, because this bit defines the EPSR.T bit on exception entry" and "On exception entry, if bit[0] of the associated vector table entry is set to 0, execution of the first instruction causes
an INVSTATE UsageFault".
I also added the new stm32f427 handler entries that all default to the default handler.

stm32f427 vector table updates

---

embed/boardloader/lowlevel.c
embed/trezorhal/rng.c

I was going through the STM32F42xx and STM32F43xx Errata sheet and found this: 2.1.6 "Delay after an RCC peripheral clock enabling". The HAL handles it better. Let's use that here.
@prusnak  heads-up to check this one in the errata sheet too:
"2.1.11 Data cache might be corrupted during Flash read-while-write operation"
Not sure if that affects how you were going to use the flash (the memory layout docs that you updated yesterday came to mind when I saw this one).

RNG: Delay after an RCC peripheral clock enabling

---

docs/bootloader.md
docs/memory.md

add notes on how to manually create a bootloader microSD and fix a typo.
i was going to make this a make target, but then figured that i didn't want to make it a dangerous footgun tool.

docs: bootloader microsd creation note and typo fix

---

SConscript.boardloader
embed/trezorhal/common.c
embed/trezorhal/rng.c
embed/trezorhal/rng.h
embed/trezorhal/stm32.c

It was easier to do this all together.
* disable stack protector for the 3 rng functions: rng_init, rng_read, and rng_get
* change return type of rng_init to void
* in multiple spots, i added type qualifiers to unsigned literals (just being pedantic)
* in stm32.c, the previous way of disabling the stack protector was still applying to all the functions in the file, no matter what i tried. so i switched to the explicit pragma for the whole file (reference gcc manual section 6.61.15).
* changed the type of `cfgr` from int to uint32_t (just being pedantic)
* removed the fpu coprocessor preprocessor stuff since it's always been enabled and always will be
* `SysTick_Handler` removed some bad comments. the machine code generated is actually the same. we want volatile specified so that reads of …

code cleanup

---

embed/extmod/modtrezorui/display-stm32.h

These are some easy simplifications that remove redundant commands due to software reset being used.
Also, the default value of power on and software reset is sleep-in mode. So, this applies:
"If software reset is sent during sleep in mode, it will be necessary to wait 120msec before sending sleep out command."
Section 15.1 in this manual, http://www.buydisplay.com/download/ic/ILI9341.pdf, is very helpful. So are the application notes at the end of the manual.
I'll have further changes in this area but these were the first simple set and I wanted to keep them easy to review.

display: remove redundant display commands and increase wait after reset

---

embed/bootloader/main.c
embed/extmod/modtrezorui/display-stm32.h
embed/extmod/modtrezorui/display.h
embed/firmware/main.c

addressing https://github.com/trezor/trezor-core/issues/50.
the diff looks a little weird. just keep in mind that i removed `display_pwm_init` and it will make more sense.
also removed some extra calls to `display_backlight`.
will probably do something similar with `periph_init` later.

boardloader, bootloader, firmware: factor out display_pwm_init

---

embed/trezorhal/sdcard.c

Addressing https://github.com/trezor/trezor-core/issues/49
With these changes, the boardloader vector table is clean.
I've tested that the boardloader SDIO stuff works with this code removed. I was able to put a new bootloader on and install a firmware using that (Nice work! Those are changes from today that I haven't reviewed other than to run functional tests so far).
The bootloader already did not have this interrupt handler in its vector table.
That left the firmware as the only place that might use SDIO interrupts. Upon further inspection, I don't think we use SDIO interrupts anywhere, so I've removed the IRQ setup etc...

SDIO: remove SDIO_IRQHandler and interrupt config

---

embed/boardloader/main.c
embed/bootloader/main.c
embed/firmware/main.c
embed/trezorhal/common.c
embed/trezorhal/common.h

don't need to call `periph_init` from each stage. just call it once in the boardloader.
future PR todos:
* i still have to research the flash caching to see if that's desirable for this particular application. (errata notes)
* some of the other things going on in periph_init also seem unnecessary.
* might further consolidate where the clocks are enabled (right now it's split between here and `display_init` for example).

boardloader, bootloader, firmware: only call periph_init in boardloader

---

embed/extmod/modtrezorui/display-stm32.h

trivial change to make the startup sequence the same for both display types for these commands.
order does not matter to the display driver for these. just makes the code a little easier to review being in numerical order. i did test these on my ILI9341.
i'm still reviewing the reset of the display commands. the manuals must have errors because they show examples using parameter values that are invalid according to the command + parameter specifications. still trying to make sense of it...

display: handle TEON and COLMOD the same for both display types

---

embed/trezorhal/stm32f4xx_hal_conf.h

This is related to the switch to STM32F42X.
This change disables the HAL from enabling the flash data cache and leaves the instruction and prefetch caches enabled. The instruction cache is required for the SDIO code to work (strange but true).
Motivation is section 2.1.11, "Data cache might be corrupted during Flash read-while-write operation" of the STM32F42xx and STM32F43xx Errata sheet:
```
When a write operation to the internal Flash memory is done, the data cache is updated to
reflect the data update. If a read operation to the other memory bank occurs during the data
cache update, the data cache content may be corrupted. In this case, subsequent read
operations from the same address (Cache hits) will be corrupted.
This issue only occurs in dual bank mode when reading (data access or …
```

boardloader: disable flash data cache

---

embed/boardloader/lowlevel.c

This removes some micropython related code that enables debug features with the intention of retrieving clock cycle counts.
It seems like a bad idea to enable this stuff (in the boardloader):
"TRCENA...Global enable for all DWT and ITM features"
"The DWT contains support for both invasive and non-invasive debug features."
No, thanks.

boardloader: stop enabling debug features to get clock cycle counts

---

embed/trezorhal/touch.c

Removing these do not change any functionality for me. These changes do rid the bootloader and firmware vector tables of the entries. I'll probably remove the USB HS interrupt handlers too, but I need to test that.
Generally, touch does not work well for me.
The bootloader touch click to continue is reliable.
But, the bootloader press to stay in bootloader mode (https://github.com/trezor/trezor-core/blob/master/embed/bootloader/main.c#L262-L268) does not work at all for me (both before and after this change).

bootloader, firmware: do not need touch interrupt handlers or to enable touch interrupts

---

SConscript.boardloader
SConscript.bootloader
SConscript.firmware
embed/trezorhal/stm32.c

The common symbol stuff was still a little sloppy (my own doing) so I cleaned it up for the boardloader, bootloader, and firmware. The variables were effectively all getting placed at the end of .bss. This does not change that. This just makes it a little more explicit that that is the intention, and it also makes multiple definitions output a warning (a sign of sloppiness).
```
COMMON         0x000000001000055c       0x20 build/boardloader/vendor/micropython/lib/stm32lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o
0x000000001000055c                pFlash
becomes
.bss.pFlash   0x00000000100004cc       0x20 build/boardloader/vendor/micropython/lib/stm32lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o
```
```
COMMON         0x00000000100010e4       0x20 …
```

build: further cleanup common symbols

---

embed/boardloader/main.c
embed/bootloader/main.c
embed/bootloader/messages.c
embed/trezorhal/image.c
embed/trezorhal/image.h

first commit simply removes the undefined behavior.
second commit, updates the function declaration and changes to not use memcpy as much.
switched one comparison to `& 511` instead of `% 512`
added a todo to do more with the expiry field. maybe what it is compared to should be an argument to the func too?

 image_parse_header: remove undefined behavior and other updates

---

embed/boardloader/lowlevel.c
embed/boardloader/main.c
embed/bootloader/main.c
embed/firmware/main.c
embed/trezorhal/flash.c

First, I trivially removed the empty `flash_init` function from the boardloader, bootloader, and firmware.
Second, I updated the flash option byte code. Notice that I changed the `opts.OptionType =` to `opts.OptionType |=`. After looking through the HAL code, I believe the new way is the correct usage.
I also made the option byte setting code erase other non-boardloader flash sectors, attempt to write the option bytes, and then loop again to check, repeating until they are set. Untested code, but probably close.

boardloader, flash: flash option bytes updates, remove flash_init

---

embed/boardloader/lowlevel.c
embed/boardloader/lowlevel.h
embed/boardloader/main.c
embed/boardloader/startup.s

The peripherals used, especially, but not limited to, the display, preclude level 6 and 7 on my dev board. The risk of enabling this detector, and continuing to use the BOR level 3 option byte, is that they affect regular users (maybe longer USB cables, bad USB ports, etc... causing voltages closer to the thresholds). The reason to enable these thresholds is to provide a level of defense against voltage glitching attacks, and/or poorly functioning components (similar to the CSS does for the HSE clock).
Level 5 seems to work for me. I tested the regular startup and also a boardloader microSD reflash.
Level 7 trips in the boardloader for me while wiping the USB HS memory. Level 6 trips in the firmware while drawing the initial screen (if it doesn't then try an all white trezor logo with …

boardloader: enable PVD programmable voltage detector and interrupt, don't clear standby flag

---

embed/bootloader/main.c

This fixes the firmware hanging after successful upload by the bootloader.
Not sure if this is the best way to handle this, but it seems to work. Notably, this works best after the 3 second wait. Otherwise, IO read errors are encountered by `trezorctl`.
Tested with `lsusb` and `python-trezor> ./trezorctl firmware_update -f ../trezor-core/build/firmware/firmware.bin`

bootloader: cleanup usb on firmware upload success before jumping to firmware

---

embed/boardloader/main.c

During testing, I was curious why disabling `INSTRUCTION_CACHE_ENABLE` caused the SD card code to fail. It turns out that it causes SDIO Rx FIFO overruns (my guess is that it is due to the extra flash waits introduced by instruction loads from flash). At least it does not look to be caused by SD power draw.
These code changes ensure that the checks fail when the read fails.

boardloader: ensure check_sdcard fails when read fails

---

src/apps/wallet/get_entropy.py

testing with `trezorctl get_entropy 4` the text was going off screen.

firmware: get_entropy text wrapping

---

embed/bootloader/messages.c

I was getting a red screen in the bootloader when I sent the unknown/invalid message `reset_device`. The message size, 22 was less than 55, and thus wrapping around to a large unsigned int. Also, the calculation was not rounding up to process all bytes. Finally, I made a small change to actually use the `iface_num` argument. I have not checked to see if a similar bug is in the firmware, but I'll look and open a separate PR if I find one.
I verified that this patch works against these tests that send messages having 1, 2, and 3 chunks:
```
python2 trezorctl reset_device
python2 trezorctl load_device -m 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'
python2 trezorctl load_device -m 'abandon abandon abandon abandon abandon abandon abandon …
```

bootloader: fix process_msg_unknown remaining chunk calculation

---

embed/unix/touch.c

This fixes the "swiping bug", swiping in emulator now feels more natural.

embed/unix: emit TOUCH_END when mouse leaves active area.

---

src/apps/ethereum/layout.py
src/apps/ethereum/sign_tx.py
src/trezor/crypto/rlp.py

- Gas is always in ether, even when sending tokens.
- Fee is computed by multiplying gas limit with gas price.
- Parse numbers already in sign_tx.
- Made rlp.encode non-recursive (also fixes not passing include_length).

Ethereum: Fix fee computation.

---

.travis.yml
Pipfile
Pipfile.lock
README.md
docs/build.md
docs/testing.md

this freezes dependency versions (most importantly right now, `rlp` is frozen at 0.6.0 which is the last that supports Travis python3.4) so that third-party changes shouldn't break the builds anymore.
Along with some nice new docs about testing.

use pipenv to run python-trezor testsuite reproducibly

---

src/apps/ethereum/layout.py
src/apps/ethereum/tokens.py
tests/test_apps.ethereum.tokens.py

When unknown token was transferred (meaning: the token address was not listed in the tokens list), we didn't treat it as a token transfer but as some arbitrary data. Since we know it is a token transfer it is beneficial to display the user such information and notify them that the token is unknown. In other words that the value is unknown, because we do not know the divisibility, nor the token suffix.
closes #198

eth: unknown token transfer is recognized and displayed as unknown

---

embed/extmod/modtrezorconfig/modtrezorconfig.c
embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2b.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2s.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-crc.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-pbkdf2.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-random.h
embed/extmod/modtrezorio/modtrezorio-flash.h
embed/extmod/modtrezorio/modtrezorio-poll.h
embed/extmod/modtrezorio/modtrezorio-sdcard.h
embed/extmod/modtrezorutils/modtrezorutils.c
embed/extmod/trezorobj.h

Continuing discussion from #191.
This PR replaces all occurrences of `mp_obj_get_int_truncated` and `mp_obj_int_get_truncated` with new helper functions.
Remaining work:

Introduce trezor_obj_get_int and trezor_obj_get_uint

---

embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2b.h

Fixes #237
It needs this PR https://github.com/trezor/trezor-crypto/pull/156 first - now this PR fails to build, because of the missing call
Locally, I used this commit in the trezor-crypto submodule - https://github.com/karel-3d/trezor-crypto/tree/fix_blake_crypto - because trezor-core fails to build with current trezor-crypto master for reasons unknown, so I cherry-picked the fix on top of the submodule.
Tested on zcash testnet, it works perfectly.

zcash: use personal field in blake2b

---

docs/emulator.md

Fixes link from the `emulator.md` to `build.md`

fix: emulator docs link

---

src/apps/ethereum/get_address.py
tests/test_apps.ethereum.get_address.py

RSKIP-60 checksum separator has changed: '0x' instead of '|'
Reference: https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md

Update RSKIP-60 checksum separator

---

src/apps/common/display_address.py
src/apps/ethereum/get_address.py
src/apps/ethereum/verify_message.py
src/apps/lisk/get_address.py
src/apps/nem/get_address.py
src/apps/wallet/get_address.py
src/apps/wallet/verify_message.py

@jpochyla I've moved the `show_qr` and `show_address` to `apps.common.display_address` (not 100% sure about the name), because it's shared between the apps. I think this is better than grabbing it from `apps.wallet`.
Also as part of that, I've added a QR code displaying into NEM's Get Address, as instructed in #227.

NEM: display QR code in get address and display address refactoring

---

Makefile
SConscript.firmware
embed/firmware/memory.ld

These changes modify the linker script to utilize also the [firmware extra](https://github.com/trezor/trezor-core/blob/master/docs/memory.md) flash area as well. Currently, the MicroPython bytecode (`frozen_mpy.o`) is moved there (around 300K).
Old layout used almost full 768K in the firmware section and nothing was used in the firmware extra section (out of 896K) (i.e. 100% and 0%).
After the change the firmware section usage is around 470K and the firmware extra section usage is around 300K (i.e. 60% and  33%).
The resulting firmware is slightly bigger (because we need to pad the first section with zeroes) totalling at around 1070K (instead of the original 770K), but this provides space for future updates.

embed/firmware: update linker to use firmware_extra section

---

src/apps/wallet/sign_tx/layout.py

Only addresses starting with bitcoincash: should get their prefix
skipped. This fixes a bug where it skips the first bytes of legacy
addresses.

signtx layout: check if address starts with prefix

---

SConscript.firmware

binctl changes firmware.bin after it's put together from p1 and p2. so just need to copy back out p1 from firmware.bin.

firmware: update flash_firmware target to use two-part flashing fix

---

SConscript.boardloader
SConscript.bootloader
SConscript.firmware
SConscript.prodtest
SConscript.reflash

this is just a little development aid so that i don't have to keep patching the scons files to build binaries that are not optimized for size. the size optimized binaries are a pain to debug because the optimizations cause a lot of jumping around in the source.
example dev kit usage with this patch applied:
`pipenv run make clean vendor build_boardloader build_bootloader build_firmware flash openocd_reset DISPLAY_ILI9341V=1 STLINK_VER=v2-1 OPTIMIZE=-Og`
simply leave off the OPTIMIZE variable to get default current behavior.

build: make it easier to build binaries optimized for debugging

---

.travis.yml
Dockerfile
Dockerfile.gcc_source
docs/build.md

There is an updated gcc-arm-none-eabi-7-2018-q2-update toolchain available at https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads. They fixed the GDB TUI so it works again in this release (aids working in the debugger).
Things seem to work for building and debugging without any grief. I didn't see any extra built time warning messages either. I did NOT diff the binaries before and after (might later). Here's what I have verified works:
tested dev kit:
- `pipenv run make clean vendor build_boardloader build_bootloader build_firmware flash openocd_reset DISPLAY_ILI9341V=1 STLINK_VER=v2-1 OPTIMIZE=-Og`
- `make openocd STLINK_VER=v2-1`
- `make gdb_boardloader`
tested prototype hardware:
- `pipenv run make clean vendor build_boardloader build_bootloader build_firmware flash …

build: update to use latest arm none eabi toolchain gcc-arm-none-eabi-7-2018-q2-update

---

embed/trezorhal/sdcard.c

Referencing https://github.com/trezor/trezor-core/issues/183 and https://github.com/trezor/trezor-core/issues/86
I was testing with the new prototype board and found this bug.
Running build of current master: `pipenv run make clean vendor build_boardloader build_bootloader build_firmware flash openocd_reset OPTIMIZE=-Og`
I found this bug by starting up with the sd card inserted.
During 10 second countdown eject sd the card (or rapidly eject and re-insert -- it's a race condition).
You'll get a red screen fatal error, like:
```
expr: sdcard_power_on()
file: embed/boardloader/main.c:52
func: check_sdcard
rev: 95416629
```
Re-insert the sd card and the system resets.
I think this bug shows that the problem of in-rush current causing a power fault while inserting a micro sd card while the sd …

boardloader: partial fix for powering off sd card

---

embed/extmod/modtrezorcrypto/modtrezorcrypto-sha3-256.h

Enables to construct keccak-sha3 so the Digest object can be used in hmac / pbkdf transparently (without need to call special digest(keccak=True) as some functions taking Digest object call digest() directly so keccak mode have to be specified before that point)

extmod-sha3: keccak parameter in the constructor

---

embed/boardloader/main.c

during the 10 second countdown, there is a race between the `sdcard_is_present` check and the `sdcard_is_present` check just within the `sdcard_power_on`.
if you pass the first and fail the second by ejecting at just the right time, you get a message like:
```
FATAL ERROR:
expr: sdcard_power_on()
file: embed/boardloader/main.c:52
func: check_sdcard
```
instead of `no SD card, aborting`
this fixes:
https://github.com/trezor/trezor-core/pull/279#issuecomment-407058722
the way to reproduce the condition with the debugger is much the same process as documented at https://github.com/trezor/trezor-core/pull/279#issue-201478305

boardloader, sdcard: avoid fatal error when card is ejected during countdown

---

SConscript.firmware
SConscript.unix
embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-ed25519.h
src/apps/cardano/__init__.py
src/apps/cardano/address.py
src/apps/cardano/cbor.py
src/apps/cardano/get_address.py
src/apps/cardano/get_public_key.py
src/apps/cardano/sign_message.py
src/apps/cardano/sign_transaction.py
src/apps/cardano/ui/__init__.py
src/apps/cardano/ui/progress.py
src/apps/cardano/verify_message.py
src/main.py
tests/test_apps.cardano.address.py
tests/test_apps.cardano.cbor.py
tests/test_apps.cardano.get_public_key.py
tests/test_apps.cardano.sign_message.py
tests/test_apps.cardano.verify_message.py
tests/test_trezor.crypto.hashlib.blake2b.py

For the support of Cardano currency was required to add cardano-specific ed25519 crypto support.
The crypto code is based on [cardano-crypto](https://github.com/input-output-hk/cardano-crypto) and [cardano-sl](https://github.com/input-output-hk/cardano-sl) - official Cardano repos.
The functions are designed to work with the [cardanolite](https://www.cardanolite.com/) wallet - a lightweight wallet for Cardano based on the official [Daedalus](https://daedaluswallet.io/) wallet. A beta version of cardanolite allowing connecting with the experimental trezor firmware will be available soon.
We are NOT official developers of Cardano, however we are developers of [www.cardanolite.com](https://www.cardanolite.com)

Add Cardano currency support

---

Dockerfile

Im not sure why, but anyway I can build with this fix
~~~sh
$ sh build-docker.sh
....
* fngprnt : 9fc8eb527f6563b283ce2f52f53bb47f4cfb6f6a7f8f76e0d951e107979ba520
dd if=build/firmware/firmware.bin of=build/firmware/firmware.bin.p1 skip=0 bs=128k count=6
6+0 records in
6+0 records out
786432 bytes (786 kB, 768 KiB) copied, 0.000696389 s, 1.1 GB/s
$
~~~

docker: protobuf stuff added

---

src/apps/ethereum/sign_tx.py

* remove chain_id restriction to support full 32bit chain_id.
* for chain_id > MAX_CHAIN_ID(2147483630) case, simply return v signature parity.
* see also https://github.com/trezor/trezor-mcu/pull/399

src/apps/ethereum: support full 32bit chain_id

---

src/apps/lisk/sign_tx.py

If a device is using for second signature calculation `sender_public_key` field must exist in a Lisk transaction message and not be replaced by the device public key. 
https://github.com/trezor/trezor-mcu/pull/351 updated with the right logic too.

lisk: fix raw transaction fields update

---

tests/unittest.py

- test cases starting with 'test_async' are executed on the async manner
- quite handy for testing serialization routines and other async tasks (e.g., Monero serialization tests)

tests: support async test cases added

---

src/apps/common/writers.py
src/apps/nem/mosaic/serialize.py
src/apps/nem/multisig/__init__.py
src/apps/nem/multisig/serialize.py
src/apps/nem/namespace/serialize.py
src/apps/nem/signing.py
src/apps/nem/transfer/serialize.py
src/apps/nem/writers.py
src/apps/ripple/serialize.py
src/apps/stellar/operations/__init__.py
src/apps/stellar/operations/serialize.py
src/apps/stellar/sign_tx.py
src/apps/stellar/writers.py
src/apps/wallet/sign_tx/overwinter_zip143.py
src/apps/wallet/sign_tx/scripts.py
src/apps/wallet/sign_tx/segwit_bip143.py
src/apps/wallet/sign_tx/signing.py
src/apps/wallet/sign_tx/writers.py
tests/test_apps.nem.multisig.aggregate_modification.py
tests/test_apps.nem.multisig.py
tests/test_apps.ripple.serializer.py

Serialization logic from altcoin and bitcoin apps was moved to `apps.common.writers`. Also:
- `write_*` functions always take the writer as first param
- `serialize_*` functions always return bytes

Unify common writer logic

---

docs/coins/README.md
docs/coins/bitcoin-path-check.svg

This documents tries to summarize what paths should be provided for which coin. If another path is provided, trezor shows a warning. Few notes:
- If NEM's _correct_ path is `44'/43'/a'`, we should allow it as well, shouldn't we? Not just the _historical_ one, similar as we do for Ethereum. And maybe the same goes for Ripple? 
- I'm putting this into docs/ folder and I think we might move all the coin's README here (as @prusnak suggested already before).
@prusnak @jpochyla @matejcik @szymonlesisz could you have a look if this seems fine?

List of used derivation paths

---

src/trezor/wire/__init__.py

Allows to use stateful message handlers
```python
wire.add(MessageType.MoneroTransactionSign, __name__, "get_address", STATE)
```

workflow: allow more arguments to the import workflow

---

src/apps/stellar/operations/serialize.py

A payment op that uses the native asset will have an asset of type 0 and no other fields populated.
This gets parsed into a protobuf message like:
```
StellarPaymentOp (67 bytes) {
amount: 10000000,
asset: StellarAssetType (2 bytes) {
type: 0,
},
destination_account: '<redacted>',
}
```
This shows up in python as an asset with a `type` but without a `code` or `issuer`. Since the asset is non-null, the code in `_write_asset` attempts to read `asset.code` and fails.
You can reproduce this by running the following command against the Model T emulator:
```
trezorctl -v stellar_sign_transaction -n "Test SDF Network ; September 2015" AAAAABXWSL/k028ZbPtXNf/YylTNS4Iz90PyJEnefPMBzbRpAAAAZAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAdV71t94srF0FKF9TmMK7sgQXPj9XH+Ma8Mv213jtSksAAAAAAAAAAACYloAAAAAAAAAA …
```

Stellar: explicitly specifying native asset in payment op causes "firmware error"

---

src/apps/lisk/sign_tx.py

This pr provides additional fixes for the previous PR https://github.com/trezor/trezor-core/pull/322
Transaction fields `sender_public_key` and `recipient_id` should be created by a device if they are not provided. 
`trezor-mcu` pr for lisk integration also updated https://github.com/trezor/trezor-mcu/pull/351/commits/34048367158d08c9a7b4e84f49656d4a7ec7c1bc

lisk: fix _update_raw_tx function for second signature calculation

---

src/apps/tezos/sign_tx.py

When creating contract, the user can immediately delegate it to baker. Therefore, we need to show this information on the screen, so we improve the security of setting that delegate.
Signed-off-by: Adrian Matejov <adrian.matejov@simplestaking.com>

Tezos: delegating contract in origination

---

src/apps/monero/signing/state.py
src/apps/monero/signing/step_01_init_transaction.py
src/apps/monero/signing/step_07_all_outputs_set.py

Monero implemented sorting fields in the `tx.extra` in the https://github.com/monero-project/monero/blob/557c17e206c697174982d28636a29c149f07f630/src/cryptonote_core/cryptonote_tx_utils.cpp#L88
The tag ordering is:
- `TX_EXTRA_TAG_PUBKEY`
- `TX_EXTRA_TAG_ADDITIONAL_PUBKEYS`
- `TX_EXTRA_NONCE`
I've implemented a small change that preserves this ordering on the Trezor so transactions do not leak info (ordering can indicate signer of the transaction) to the blockchain.
The only required change was to move `TX_EXTRA_NONCE` to the end of the extra field - so I've added `state.extra_nonce` field which is added to the `tx.extra` after all previous tags are in place.
I've also did some small refactoring to minimize buffer reallocation for extras.

xmr: sort extra fields

---

src/apps/monero/key_image_sync.py
src/apps/monero/layout/confirms.py

Adds very simple progress view for key image sync so user knows Trezor is working on the sync (otherwise it could look like something went wrong / frozen)

xmr: key image sync progress info

---

embed/extmod/modtrezorconfig/modtrezorconfig.c
embed/extmod/modtrezorconfig/norcow.c
embed/extmod/modtrezorconfig/norcow_config.h
embed/extmod/modtrezorconfig/storage.c
embed/extmod/modtrezorconfig/storage.h
src/apps/management/change_pin.py
src/apps/management/load_device.py
src/apps/management/recovery_device.py
src/apps/management/reset_device.py
src/boot.py
tests/test_trezor.config.py

This commit accomplishes several goals:
1) it removes any upy dependencies from storage.c/storage.h
2) ui wait callback is set during config_init and storage_init, which allows to simplify the code dramatically

embed/extmod/modtrezorconfig: refactor PIN UI wait callback

---

docs/build.md

This package was missing while build (``` make build_unix ```)

Added missing package for OS X

---

tests/run_tests_device_emu.sh

Running `make test_emu` in trezor-core doesn't work for me. trezor-core/tests/unittest.py overshadows the standard library unittest, so pytest is unable to start at all (exception below). 
```
(trezor-core) bash-3.2$ make test_emu
cd tests ; ./run_tests_device_emu.sh 
Traceback (most recent call last):
File "/Users/tibor/.virtualenvs/trezor-core-JdiA6MQI/bin/pytest", line 7, in <module>
from pytest import main
File "/Users/tibor/.virtualenvs/trezor-core-JdiA6MQI/lib/python3.7/site-packages/pytest.py", line 13, in <module>
from _pytest.debugging import pytestPDB as __pytestPDB
File "/Users/tibor/.virtualenvs/trezor-core-JdiA6MQI/lib/python3.7/site-packages/_pytest/debugging.py", line 8, in <module>
from doctest import UnexpectedException
File …
```

Fixing make test_emu in some environments.

---

src/apps/monero/signing/step_01_init_transaction.py

Typo in tail differentiating tag caused invalid short payment id encryption. was 0x8B, should have been 0x8D.
Correct computation: 
```python
enc_payment_id = payment_id ^ cn_fast_hash(derivation + b'\x8D')
```
Tail tag `0x8D` was mistyped as `0x8B` which yields a different hash which is used for XOR. 
No funds are lost, but payment ID is incorrect which can cause payment linking problems when using exchanges / markets. 
Recipient of the message can recompute the payment ID:
```python
derivation = 8 * view_key_private * tx_key_public
correct_payment_id = enc_payment_id ^ cn_fast_hash(derivation + b'\x8D')
```
OR from the wrongly decrypted plain payment id:
```python
correct_payment_id = wrongly_decrypted_payment_id ^ cn_fast_hash(derivation + b'\x8D') ^ cn_fast_hash(derivation + b'\x8B') …
```

xmr: payment ID computation fix

---

Pipfile.lock
src/apps/wallet/sign_tx/helpers.py

otherwise the values are repeated in every subsequent TxRequest
this also fixes a build failure in the new Dash test, where the `TxRequestDetailsType` only specifies `request_index`, but actually receives the `extra_data` fields from the previous round.
This can also be fixed on python-trezor side (so that the child protobufs matching is relaxed, same as the top-level matching), but I decided to keep the strict equality check for now, as it allowed us to catch this minor bug :)

wallet/signing: clear extra_data fields after we're done with them

---

docs/git/hooks/pre-push

Quite frequently my code fails on CI because I've simply forgotten to run `make templates` or `make style`. This git hook runs both and if the it does not succeed it aborts the push.
If interested, insert the file into `.git/hooks`.

Add git pre-push hook to docs

---

Makefile
help.awk

1. Fixed "code generation" label (there was ` ##` instead of `:`)
2. Added nice spacing after each group of commands.
3. Moved the awk command to a separate file for readability.

make help - typo fix, add spacing & refactor

---

Pipfile.lock
src/apps/monero/__init__.py
src/apps/monero/get_tx_keys.py
src/apps/monero/layout/confirms.py
src/apps/monero/live_refresh.py
src/apps/monero/misc.py
src/apps/monero/signing/step_10_sign_final.py
src/apps/monero/xmr/key_image.py
tests/run_tests_device_emu_monero.sh

Relates to: https://github.com/trezor/trezor-common/pull/255
This PR adds get_tx_key and live_refresh features. 
- get_tx_key supports retrieval of private tx keys (not spend keys, just random transaction privates, `r` and additional private keys if applicable) required by users to check the transaction or when resolving disputes with the recipient
- get_tx_key supports to return transaction derivations = private tx key * public view key. This enables to compute tx_proof for outgoing transactions which are also a nice tool when resolving disputes, provides better protection as tx private key are not exported in this case.
- live refresh enables computation of key images on the fly during the refresh. This helps to completely avoid key image sync and enables to use the Trezor with …

xmr: get_tx_keys, live_refresh

---

src/apps/fido_u2f/knownapps.py

Trezor Model T can display 20 chars max, which causes this name to display as "2f.bin.coffee checke".

u2f: "u2f.bin.coffee checker" -> "u2f.bin.coffee"

---

docs/coins/README.md

This is a "refactoring" of the coins document, done as a side-effect of adding the new coins that currently have open PRs:
1. EOS #397
EOS is a candidate for SLIP-48 paths, but nobody uses these, and it seems simpler to go with a more basic scheme. Other vendors use Ripple-like paths: https://github.com/trezor/trezor-core/pull/397#issuecomment-448278291
2. Ontology #323 
Currently they seem to use Ethereum-like paths, which is the stupidest of the bunch: https://github.com/trezor/trezor-core/pull/323#issuecomment-415752419
There's also a possibility to allow NEO SLIP-44 path: https://github.com/trezor/trezor-core/pull/323#issuecomment-415769465
We prooobably don't want that, but maybe.
I'm hoping that it would at least be possible to use Ripple-like path, but I'm waiting for the …

Coins doc update (WIP)

---

src/apps/cardano/layout/__init__.py

Taint pages to ensure the texts are rendered when swiping. Closes #497

cardano: taint pages to prevent blank screen

---

embed/extmod/modtrezorui/display-stm32_1.h
embed/extmod/modtrezorui/display-stm32_t.h
embed/extmod/modtrezorui/display-unix.h
embed/extmod/modtrezorui/display.h
embed/unix/touch.c

Base of architecture for UI tests and workflow documentation.

Skip identical screenshots in display.save

---

SConscript.unix
embed/unix/mpconfigport.h
src/trezor/ui/__init__.py
src/trezor/utils.py

If environment variable `TREZOR_SAVE_SCREEN` is set, every screen refresh produces a screenshot in current directory. Useful for integration testing and generating workflow documentation.

Save screen after every refresh

---

src/trezor/utils.py

I've noticed that when comparing `__slots__`' attributes, a new dictionary is being created.
To benefit from improved speed and memory usage we should access these attributes directly :muscle:

utils: optimize __slots__ comparison

---

.gitmodules
SConscript.firmware
SConscript.unix
embed/extmod/modtrezorcrypto/modtrezorcrypto-secp256k1.h
embed/extmod/modtrezorcrypto/modtrezorcrypto-secp256k1_zkp.h
embed/extmod/modtrezorcrypto/modtrezorcrypto.c
embed/firmware/memory_T.ld
src/trezor/crypto/curve.py
tests/test_trezor.crypto.curve.secp256k1.py

This includes the https://github.com/ElementsProject/secp256k1-zkp library (which is a fork from  sipa/secp256k1 used in Bitcoin Core)  and uses it for signing transactions and signing and verifying messages for ECDSA on the secp256k1 curve.
The Ethereum app is left untouched. I assume because they use Keccak-256 as a message digest and not SHA256. @apoelstra 
This is the first step towards solving #282.
Some background to understand the open issues below:
secp256k1-zkp (and in fact sipa/secp256k1) relies on two precomputation tables to speed up signing and for verification.  secp256k1(-zkp) supports that the precomputed table values for the signing table are stored in the executable (by defining `USE_ECMULT_STATIC_PRECOMPUTATION`) and thus do not need to be created at running time.
It's …

Add extmod for secp256k1-zkp
